INSERT INTO words (word, length, is_solution, language) VALUES
('TERMO',  5, TRUE,  'pt-BR'),
('CARRO',  5, TRUE,  'pt-BR'),
('BARCO',  5, TRUE,  'pt-BR'),
('CAMPO',  5, TRUE,  'pt-BR'),
('CASAS',  5, TRUE,  'pt-BR'),
('CONTA',  5, TRUE,  'pt-BR'),
('CRISE',  5, TRUE,  'pt-BR'),
('CORPO',  5, TRUE,  'pt-BR'),
('CURSO',  5, TRUE,  'pt-BR'),
('DOCES',  5, TRUE,  'pt-BR'),
('FALAR',  5, TRUE,  'pt-BR'),
('FORTE',  5, TRUE,  'pt-BR'),
('GRATO',  5, TRUE,  'pt-BR'),
('HOTEL',  5, TRUE,  'pt-BR'),
('JOGAR',  5, TRUE,  'pt-BR'),
('LARGO',  5, TRUE,  'pt-BR'),
('LEITE',  5, TRUE,  'pt-BR'),
('LENTO',  5, TRUE,  'pt-BR'),
('LITRO',  5, TRUE,  'pt-BR'),
('LIVRO',  5, TRUE,  'pt-BR'),
('LOUVO',  5, TRUE,  'pt-BR'),
('LUNAR',  5, TRUE,  'pt-BR'),
('MAIOR',  5, TRUE,  'pt-BR'),
('MARCO',  5, TRUE,  'pt-BR'),
('MATAR',  5, TRUE,  'pt-BR'),
('MAURO',  5, TRUE,  'pt-BR'),
('MILHO',  5, TRUE,  'pt-BR'),
('MOLHO',  5, TRUE,  'pt-BR'),
('MUNDO',  5, TRUE,  'pt-BR'),
('NEGRO',  5, TRUE,  'pt-BR'),
('NINHO',  5, TRUE,  'pt-BR'),
('NOITE',  5, TRUE,  'pt-BR'),
('NORTE',  5, TRUE,  'pt-BR'),
('NOVOS',  5, TRUE,  'pt-BR'),
('OLHAR',  5, TRUE,  'pt-BR'),
('OUTRO',  5, TRUE,  'pt-BR'),
('OVAIS',  5, TRUE,  'pt-BR'),
('PADRE',  5, TRUE,  'pt-BR'),
('PAIOL',  5, TRUE,  'pt-BR'),
('PALCO',  5, TRUE,  'pt-BR'),
('PAPEL',  5, TRUE,  'pt-BR'),
('PEDIR',  5, TRUE,  'pt-BR'),
('PEDRA',  5, TRUE,  'pt-BR'),
('PEIXE',  5, TRUE,  'pt-BR'),
('PENSO',  5, TRUE,  'pt-BR'),
('PERDA',  5, TRUE,  'pt-BR'),
('PILHA',  5, TRUE,  'pt-BR'),
('PISTA',  5, TRUE,  'pt-BR'),
('PLANO',  5, TRUE,  'pt-BR'),
('PODER',  5, TRUE,  'pt-BR'),
('PONTO',  5, TRUE,  'pt-BR'),
('PORTA',  5, TRUE,  'pt-BR'),
('POSSE',  5, TRUE,  'pt-BR'),
('PRAIA',  5, TRUE,  'pt-BR'),
('PRATO',  5, TRUE,  'pt-BR'),
('PRAZO',  5, TRUE,  'pt-BR'),
('PROVA',  5, TRUE,  'pt-BR'),
('PUDIM',  5, TRUE,  'pt-BR'),
('PULSO',  5, TRUE,  'pt-BR'),
('QUADRO', 6, TRUE,  'pt-BR'),
('RADIO',  5, TRUE,  'pt-BR'),
('RAMOS',  5, TRUE,  'pt-BR'),
('RAPAZ',  5, TRUE,  'pt-BR'),
('RECUO',  5, TRUE,  'pt-BR'),
('REINO',  5, TRUE,  'pt-BR'),
('RENDA',  5, TRUE,  'pt-BR'),
('RITMO',  5, TRUE,  'pt-BR'),
('ROSTO',  5, TRUE,  'pt-BR'),
('ROTUM',  5, FALSE, 'pt-BR'),
('SAGAZ',  5, TRUE,  'pt-BR'),
('SAIDA',  5, TRUE,  'pt-BR'),
('SALVO',  5, TRUE,  'pt-BR'),
('SANTO',  5, TRUE,  'pt-BR'),
('SAUDE',  5, TRUE,  'pt-BR'),
('SECAR',  5, TRUE,  'pt-BR'),
('SENHA',  5, TRUE,  'pt-BR'),
('SENSO',  5, TRUE,  'pt-BR'),
('SERVO',  5, TRUE,  'pt-BR'),
('SIGLA',  5, TRUE,  'pt-BR'),
('SIMAO',  5, FALSE, 'pt-BR'),
('SOFRE',  5, TRUE,  'pt-BR'),
('SOLTA',  5, TRUE,  'pt-BR'),
('SONHO',  5, TRUE,  'pt-BR'),
('SORTE',  5, TRUE,  'pt-BR'),
('SURDO',  5, TRUE,  'pt-BR'),
('TALCO',  5, TRUE,  'pt-BR'),
('TANTO',  5, TRUE,  'pt-BR'),
('TAQUE',  5, FALSE, 'pt-BR'),
('TARDE',  5, TRUE,  'pt-BR'),
('TENDA',  5, TRUE,  'pt-BR'),
('TIGRE',  5, TRUE,  'pt-BR'),
('TINHA',  5, TRUE,  'pt-BR'),
('TINTO',  5, TRUE,  'pt-BR'),
('TIPOS',  5, TRUE,  'pt-BR'),
('TOCHA',  5, TRUE,  'pt-BR'),
('TORTO',  5, TRUE,  'pt-BR'),
('TOTAL',  5, TRUE,  'pt-BR'),
('TOURO',  5, TRUE,  'pt-BR'),
('TRAVE',  5, TRUE,  'pt-BR'),
('TREVO',  5, TRUE,  'pt-BR'),
('TRIGO',  5, TRUE,  'pt-BR'),
('TURMA',  5, TRUE,  'pt-BR'),
('ULTRA',  5, TRUE,  'pt-BR'),
('URGIR',  5, FALSE, 'pt-BR'),
('USUAL',  5, TRUE,  'pt-BR'),
('VALER',  5, TRUE,  'pt-BR'),
('VALOR',  5, TRUE,  'pt-BR'),
('VERDE',  5, TRUE,  'pt-BR'),
('VERSO',  5, TRUE,  'pt-BR'),
('VOLTA',  5, TRUE,  'pt-BR'),
('VOMIT',  5, FALSE, 'pt-BR'),
('VOTAR',  5, TRUE,  'pt-BR'),
('ZEBRA',  5, TRUE,  'pt-BR')
    ON CONFLICT (word, language) DO NOTHING;

INSERT INTO daily_words (word_id, game_date, language)
SELECT
    w.id,
    CURRENT_DATE + (row_number() OVER (ORDER BY w.id) - 1)::INT,
    'pt-BR'
FROM words w
WHERE w.is_solution = TRUE
  AND w.language    = 'pt-BR'
  AND w.length      = 5
ORDER BY w.id
    LIMIT 30
ON CONFLICT (game_date, language) DO NOTHING;